# Generated by Django 5.1.2 on 2024-11-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_remove_userimage_is_favorite_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='image_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='userimage',
            name='document_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=10),
            preserve_default=False,
        ),
    ]
