# Generated by Django 5.1.2 on 2024-12-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_rename_image_url_userimage_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
