# Generated by Django 5.1.2 on 2024-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_userimage_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userimage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='vault.tag'),
        ),
    ]
