# api/Dockerfile
FROM python:3.10

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app code
COPY . .

# Expose the port and define the command
EXPOSE 8000
CMD ["python", "mains.py"]

